Repository a11yj/accrefs, pull requests merged in 2019-08, with the labels that each got.

#36 ピンク色の本という表記を、デザイニングWebアクセシビリティへ変更
  src/md/post/デザイニングWebアクセシビリティ.md
  src/md/tag/何から手を着けていいのか分からないときは.md
Labels: bug

#37 翻訳文書関連の調整
  src/md/post/epub-accessibility-guidelines-ja.md
  src/md/post/epub-accessibility-ja.md
  src/md/post/epub-accessibility-techniques-ja.md
  src/md/post/how-to-meet-wcag2-ja.md
  src/md/post/techniques-for-wcag2.0-ja.md
  src/md/post/understanding-wcag2.0-ja.md
  src/md/post/wai-aria-ja.md
  src/md/post/wcag2.0-ja.md
  src/md/post/wcag2.1-ja.md
Labels: bug, good first issue

#41 ホームにページタイトルを設定
  src/_includes/base.pug
  src/index.11tydata.json
Labels: enhancement

#40 「おもしろ動画・音楽」の記事を修正する
  src/references/00071.md
  src/references/00095.md
Labels: bug

#43 ホームではog:titleにサイトタイトルを使用する
  src/_includes/base.pug
Labels: bug

#44 meta descriptionにタグの説明を設定
  src/_includes/base.pug
Labels: enhancement

#45 タグ詳細に非可視ラベルを追加
  src/tag.pug
Labels: bug

#46 タグと参考資料のデータの記述方法のテストを追加
  lint-content-format.js
  package-lock.json
  package.json
  src/references.pug
  src/references/00093.md
  src/references/00094.md
  src/references/00112.md
  src/tag.pug
Labels: enhancement
