Repository a11yj/accrefs, pull requests merged in 2019-09, with the labels that each got.

#57 フッターにGitHubリポジトリへのリンクを追加
  src/_includes/base.pug
Labels: enhancement

#61 404ページの追加
  src/404.11tydata.json
  src/404.pug
Labels: enhancement

#59 参考資料の一覧をファイル名順に並び替え
  .eleventy.js
Labels: bug

#60 見出しにプロポーショナルメトリクスを適用
  src/assets/main.css
Labels: enhancement

#62 404ページからcanonical URLの記述を削除
  src/404.11tydata.json
  src/_includes/base.pug
Labels: invalid

#53 高度なリクエスト方法を追記する
  .github/ISSUE_TEMPLATE/--------------.md
  .github/ISSUE_TEMPLATE/add_request.md
  INSTALLATION.md
  README.md
Labels: documentation, enhancement

#63 マークダウンの構文を修正
  src/references/00055.md
Labels: bug

#64 アイコンに隣接するラベルの折り返し方法を修正
  src/assets/main.css
Labels: bug

#65 インラインリストのアイテム同士の区分方法の変更
  src/_includes/base.pug
  src/assets/main.css
  src/references.pug
Labels: enhancement

#66 概要文追加や記載内容の修正
  src/_data/tags.json
  src/references/00104.md
  src/references/00127.md
  src/references/00147.md
  src/references/00148.md
  src/references/00200.md
Labels: bug, enhancement

#50 掲載要綱を追記する
  README.md
Labels: documentation, enhancement, question

#54 ライセンスを追記する
  LICENSE
  README.md
Labels: documentation, enhancement

#51 リンクの追加修正方法を追記する
  README.md
Labels: documentation, enhancement

#52 リンク以外のリクエスト方法を追記する
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: documentation, enhancement

#68 [スタイル] 見出し2相当のセクション同士の分割方法の見直し
  src/404.pug
  src/assets/main.css
  src/index.pug
Labels: enhancement

#69 [スタイル] CSS内のタイポの修正
  src/assets/main.css
Labels: bug

#71 [スタイル] 訪問済みリンクのカラーコントラストを改善
  src/assets/main.css
Labels: enhancement

#72 [WAI-ARIA] <article>要素にアクセシブルな名前を提供
  src/index.pug
  src/references.pug
  src/tag.pug
Labels: enhancement

#48 READMEを整える
  .github/ISSUE_TEMPLATE/--------------.md
  .github/ISSUE_TEMPLATE/add_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  INSTALLATION.md
  LICENSE
  README.md
  package-lock.json
  package.json
Labels: documentation, enhancement
